const HOST = process.env.HOST || '0.0.0.0';
const PORT = process.env.PORT ? parseInt(process.env.PORT, 10) : 3000;
const WS_PATH = process.env.WS_PATH || '/game-ws';

const MAX_SPEED = 20;

const DEFAULT_HP = 100;
const DEFAULT_ENERGY = 100;

const NPC_SPAWN_POINTS = [
  { id: 'npc-1', x: -5, y: 0 },
  { id: 'npc-2', x: 5, y: 0 },
];
const NPC_SPAWN_NEAR_PLAYER_RADIUS = 2;

const NPC_STATE_BROADCAST_PERIOD_MS = 100;
const GRID_SIZE = 1;
const CELL_CENTER_OFFSET_X = 0.5;
const CELL_CENTER_OFFSET_Y = 0.5;
const NPC_AI_TICK_MS = 200;
const NPC_ATTACK_DAMAGE = 10;
const NPC_ATTACK_COOLDOWN = 0.6;
const NPC_ATTACK_COOLDOWN_AFTER_MOVE = 0.3;
const NPC_AGGRO_RANGE = 4;
const NPC_LOSE_RANGE = 6;
const NPC_MEMORY_DURATION = 3;
const NPC_ATTACK_RANGE = 1.5;
const NPC_ATTACK_WINDOW_SECONDS = 0.2;
const NPC_ATTACK_FACING_DOT = 0.5;
const NPC_ARROW_HITBOX_SIZE_X = 0.23;
const NPC_ARROW_HITBOX_SIZE_Y = 0.01;
const NPC_ARROW_HITBOX_OFFSET_X = 0.51;
const NPC_ARROW_HITBOX_OFFSET_Y = 0.015;
const NPC_ARROW_HITBOX_SCALE = 0.7;
const PLAYER_HITBOX_SIZE_X = 0.63;
const PLAYER_HITBOX_SIZE_Y = 0.125;
const PLAYER_HITBOX_OFFSET_X = 0.30870003;
const PLAYER_HITBOX_OFFSET_Y = 0.0075;
const NPC_RETREAT_HEALTH_THRESHOLD = 0.3;
const NPC_RETREAT_DISTANCE = 3;
const NPC_RETREAT_CHANCE = 0.7;
const NPC_PREDICTION_TIME = 0.5;
const NPC_ALIGN_SNAP_FACTOR = 0.25;
const NPC_PATROL_WAIT_TIME = 1;
const NPC_LOOP_PATROL = true;

const ENERGY_SEGMENTS = 10;
const ENERGY_SEGMENT_VALUE = DEFAULT_ENERGY / ENERGY_SEGMENTS;
const ENERGY_SEGMENT_PERIOD = 5;
const ENERGY_EMPTY_EXTRA_DELAY_MIN = 5;
const ENERGY_EMPTY_EXTRA_DELAY_MAX = 30;
const ENERGY_REGEN_TICK = 1;

module.exports = {
  HOST,
  PORT,
  WS_PATH,
  MAX_SPEED,
  DEFAULT_HP,
  DEFAULT_ENERGY,
  NPC_SPAWN_POINTS,
  NPC_SPAWN_NEAR_PLAYER_RADIUS,
  NPC_STATE_BROADCAST_PERIOD_MS,
  GRID_SIZE,
  CELL_CENTER_OFFSET_X,
  CELL_CENTER_OFFSET_Y,
  NPC_AI_TICK_MS,
  NPC_ATTACK_DAMAGE,
  NPC_ATTACK_COOLDOWN,
  NPC_ATTACK_COOLDOWN_AFTER_MOVE,
  NPC_AGGRO_RANGE,
  NPC_LOSE_RANGE,
  NPC_MEMORY_DURATION,
  NPC_ATTACK_RANGE,
  NPC_ATTACK_WINDOW_SECONDS,
  NPC_ATTACK_FACING_DOT,
  NPC_ARROW_HITBOX_SIZE_X,
  NPC_ARROW_HITBOX_SIZE_Y,
  NPC_ARROW_HITBOX_OFFSET_X,
  NPC_ARROW_HITBOX_OFFSET_Y,
  NPC_ARROW_HITBOX_SCALE,
  PLAYER_HITBOX_SIZE_X,
  PLAYER_HITBOX_SIZE_Y,
  PLAYER_HITBOX_OFFSET_X,
  PLAYER_HITBOX_OFFSET_Y,
  NPC_RETREAT_HEALTH_THRESHOLD,
  NPC_RETREAT_DISTANCE,
  NPC_RETREAT_CHANCE,
  NPC_PREDICTION_TIME,
  NPC_ALIGN_SNAP_FACTOR,
  NPC_PATROL_WAIT_TIME,
  NPC_LOOP_PATROL,
  ENERGY_SEGMENTS,
  ENERGY_SEGMENT_VALUE,
  ENERGY_SEGMENT_PERIOD,
  ENERGY_EMPTY_EXTRA_DELAY_MIN,
  ENERGY_EMPTY_EXTRA_DELAY_MAX,
  ENERGY_REGEN_TICK,
};
